version: '3'

services:

  db:
    image: mysql
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=2280
    - MYSQL_DATABASE=piraterDB
    volumes:
    - db-data:/var/lib/mysql

  
  web_server:
    image: nginxapp
    restart: always
    ports:
    - 80:80
    network_mode: host
    volumes:
    - ./logs/server:/var/log/nginx
    # - ./data/images:/usr/share/nginx
    # - ./data/static:/usr/share/nginx/html
    # - nginx-data:/etc/nginx
    # - 80:80


    # my_app:
    #     image: app:1.0
    #     ports:
    #     - 8080:8080
volumes:
    db-data:
        driver: local
    # nginx-data:
        # driver: local