version: '3'

services:

  db:
    image: mysql
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=2280
    - MYSQL_DATABASE=piraterDB
    - TZ=Europe/Moscow
    command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log/log.log
    volumes:
    - db-data:/var/lib/mysql
    - ./logs/mysql:/var/lib/mysql/general-log.log

  
  web_server:
    image: nginxapp
    restart: always
    ports:
    - 80:80
    network_mode: host
    volumes:
    - ./logs/server:/var/log/nginx


  cookie_db:
    image: redis
    restart: always
    ports:
    - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass 1337
    volumes:
    - cookie-data:/data
    - ./logs/redis:/var/log

    
    # my_app:
    #     image: app:1.0
    #     ports:
    #     - 8080:8080

volumes:
    db-data:
        driver: local
    cookie-data:
        driver: local