server:
    addr: "goapp-2"
    port: 8008

log:
    level: "debug"

sql_db:
    user: "root"
    pass: "2280"
    name: "piraterDB"
    addr: "db"
    port: 3306

cookie_db:
    pass: "1337"
    addr: "cookie_db"
    port: 6379
    max_connections: 10